cant_cedears = { 'AAPL.BA':54,'BABA.BA':12,'COST.BA':6,'GE.BA':22,'GOOGL.BA':169,'GS.BA':11,'JPM.BA':57,'KO.BA':16,'NVDA.BA':420,'WMT.BA':216,'YPFD.BA':6 }
cedears = ["AAPL.BA","BABA.BA","COST.BA","GE.BA","GOOGL.BA","GS.BA",'JPM.BA',"KO.BA","NVDA.BA","WMT.BA","YPFD.BA"]
ratios = { 'AAPL.BA':20,'AMZN.BA':144,'BABA.BA':9,'COST.BA':48,'GE.BA':8,'GOOGL.BA':58,'GS.BA':13,'JPM.BA':15,'KO.BA':5,'MSFT.BA':30,'NVDA.BA':24,'WMT.BA':18,'XOM.BA':10,'YPFD.BA':1 }
tickers = ["AAPL","BABA","COST","GE","GOOGL","GS","JPM","KO","NVDA","WMT","YPF"]
